### ISSUE TITLE
Use snowboy train API to create hotwords

### ISSUE THREAD

**Issue by taostaos** [alexylem/jarvis#172] opened 2016-10-10 14:59 UTC
Hi, it could be great to generate pmdl files directly from Jarvis, using the [api](http://docs.kitt.ai/snowboy/#api-v1-train) they provide.

I might give it a try if I have some time available (in a long time)

**Comment by alexylem** [comment] 2016-10-10 17:31
Definitely a great improvement I'll seriously consider!

**Comment by taostaos** [comment] 2016-10-12 08:06
I'll do it, I started yesterday, got a model file, need now to move it to the correct folder and test the model. Do you want the poc in shell or python?

**Comment by alexylem** [comment] 2016-10-12 09:17
Many thanks for proposing!
Jarvis is primarily in `shell` so that would be my pick.
However, `snowboy` STT has already some pieces in `python`. So if you are more comfortable with `python` (I am too) go ahead (if the code is simpler and don't require additional dependencies).

**Comment by taostaos** [comment] 2016-10-13 12:55
[First draft](https://github.com/taostaos/jarvis-snowboy-hotword-poc)

Based on the sample found on the snowboy doc. I'll test it asap

**Comment by alexylem** [comment] 2016-10-13 16:43
Great piece of code! I'm looking forward your testing to see if it works. It will be a piece of cake to integrate in Jarvis 😄

**Comment by taostaos** [comment] 2016-10-14 21:53
Fix and tested. You can give it a try ! don't forget to put your snowboy token n_n

**Comment by alexylem** [comment] 2016-10-15 08:10
Integrating into Jarvis Core...

**Comment by alexylem** [comment] 2016-10-15 08:49
To make the integration simpler, I drop the non-required parameters (language, age, gender, microphone).

**Comment by alexylem** [comment] 2016-10-15 11:10
@taostaos have you tested Jarvis with you freshly trained model?
For now I have this error:
```
Jarvis: Waiting to hear 'Jarvis'
Alex: (listening...)
DEBUG: models=Jarvis,snowboy
ERROR (ClassifyModels():pipeline-detect.cc:446) PipelineDetect: undefined model type detected. Most likely you provided the wrong model.
```

**Comment by alexylem** [comment] 2016-10-15 11:15
Ok I have a **400 Bad Request**
```
Note: Unnecessary use of -X or --request, POST is already inferred.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 52.8.74.71...
* Connected to snowboy.kitt.ai (52.8.74.71) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate: *.kitt.ai
* Server certificate: COMODO RSA Domain Validation Secure Server CA
* Server certificate: COMODO RSA Certification Authority
* Server certificate: AddTrust External CA Root
  0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0> POST /api/v1/train/ HTTP/1.1
> Host: snowboy.kitt.ai
> User-Agent: curl/7.49.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 216276
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
} [16384 bytes data]
 90  211k    0     0   90  192k      0  72356  0:00:02  0:00:02 --:--:-- 72362* We are completely uploaded and fine
100  211k    0     0  100  211k      0  52080  0:00:04  0:00:04 --:--:-- 52089< HTTP/1.1 400 Bad Request
< Allow: POST, OPTIONS
< Content-Type: application/json
< Date: Sat, 15 Oct 2016 11:13:20 GMT
< Server: nginx/1.4.6 (Ubuntu)
< Vary: Cookie
< X-Frame-Options: SAMEORIGIN
< Content-Length: 170
< Connection: keep-alive
< 
{ [170 bytes data]
100  211k  100   170  100  211k     33  43009  0:00:05  0:00:05 --:--:-- 56899
* Connection #0 to host snowboy.kitt.ai left intact
```

**Comment by alexylem** [comment] 2016-10-15 11:23
Ok I have this as a return from the API:
```json
{
"microphone":["This field may not be null."],
"universal_hotword":
  {"name":["UniversalHotword with this name already exists."],
  "language":["This field may not be null."]}
}
```

**Comment by taostaos** [comment] 2016-10-15 11:42
Yep, I'have tested the new model, and it works fine.

I'm pretty sure that you need at least the language parameter. You can try with all the parameters, and remove them one by one if it's working. I think that is you don't specify the language , the api try to create a universal hotword, which can't be done.

**Comment by alexylem** [comment] 2016-10-15 11:45
Thanks, I got confused by the doc which states that those parameters are not required.
I pass now the language (from Jarvis settings) and the microphone (which I detect)
Just an issue to fix with spaces in hotwords and it should be fine...

**Comment by taostaos** [comment] 2016-10-15 12:24
Hum, I handle this, you call the script with one parameter : ./script.sh turn_on_the_light.

I call the api with the hotword name "turn on the light" , and generate the model turn_on_the_light.pmdl.

Then if I read correctly your hotword documentation, we just need to add to jarvis-command  TURN*ON*THE*LIGHT==...  

Right?

**Comment by alexylem** [comment] 2016-10-15 15:29
Absolutely, I'm integrating your code into the core, I don't keep your file as standalone.
I'm almost done, I had to leave for a couple of hours.

Yes:
```
TURN ONE THE LIGHT==...
```
with a `Turn on the light.pmdl` will be triggered fine.

**Comment by alexylem** [comment] 2016-10-15 16:34
Also showing a progress bar on the upload:
![image](https://cloud.githubusercontent.com/assets/11017174/19411659/05c917e8-9306-11e6-9643-72ec8fd7491f.png)
I'm almost done!

**Comment by taostaos** [comment] 2016-10-15 17:19
Nice !

**Comment by alexylem** [comment] 2016-10-15 19:31
I face an issue with the training of the hotword "jarvis":
![image](https://cloud.githubusercontent.com/assets/11017174/19412837/929d656c-931e-11e6-89fe-64ae9b4aaff2.png)
For other names, it is fine.

I logged a ticket at snowboy repo:
https://github.com/Kitt-AI/snowboy/issues/75

**Comment by taostaos** [comment] 2016-10-15 20:39
I feel like when it's a universal hotword, we need to call the improve api, but I didn't look if it returns the umdl file  (universal model).

on the other hand, it looks like a universal hotword is one in english (or maybe without a language defined).

**Comment by alexylem** [comment] 2016-10-15 20:44
For what I understood it becomes Universal when it has more than X samples (trained by enough people so that it should work with everyone, like `snowboy`).
For `jarvis` it's 200. Looks like this number depends on the size of the hotword.
I haven't tried `improve` either, but to me the API should be smart enough to create/improve and even provide you the universal model if it exists already. Let's see what they say in the ticket.

**Comment by alexylem** [comment] 2016-10-15 21:18
Implemented. Please update & let me know if all ok.
I leave the ticket open for the issue with `jarvis.pmdl` model discussed [here](https://github.com/Kitt-AI/snowboy/issues/75).

Little bonus of the commit: colors for better clarify
![image](https://cloud.githubusercontent.com/assets/11017174/19413446/9c9666d6-932d-11e6-98a7-4627abc26c28.png)

**Comment by alexylem** [comment] 2016-10-15 21:21
@taostaos many thanks for your contribution.
I added you in the credits page:
http://domotiquefacile.fr/jarvis/content/credits

**Comment by alexylem** [comment] 2016-10-16 19:59
They confirmed the bug in [my ticket](https://github.com/Kitt-AI/snowboy/issues/75#issuecomment-254031686). I temporarily force the language to `en` as a workaround.

**Comment by taostaos** [comment] 2016-10-17 08:09
Nice !

**Comment by alexylem** [comment] 2016-10-25 19:30
The guy from Snowboy has fixed by ticket. Changing now hardcoded language from `en` to use user's language...

**Closed** 2016-10-25 19:31 UTC
Labels: enhancement

**Comment by physicien** [comment] 2016-10-26 03:01
Is it still possible to manually add the hotword? I ask because we can train a hotword with several people on the site. In addition, every time I said his name, he starts conversation mode, but saying he does not understand his name.

**Comment by alexylem** [comment] 2016-10-26 07:37
@physicien yes it is still possible by following [the manual procedure](domotiquefacile.fr/jarvis/content/snowboy) on the site.
However, if he says he doesn't understand his name, that's a big I used to have.
Could you please dump the console in troubleshooting mode to help me investigate?
Thanks!

**Comment by taostaos** [comment] 2016-10-26 08:17
>  I ask because we can train a hotword with several people on the site.

Currently, the snowboy's train API only provide the training of a personal model, with only 3 sample of audio, so that's not possible.

> In addition, every time I said his name, he starts conversation mode, but saying he does not understand his name.

Feels like you might have duplicated model, check sonwboy's resource folder.

@alexylem dead link =P

**Comment by alexylem** [comment] 2016-10-26 08:29
Link fixed 😄

**Comment by physicien** [comment] 2016-10-26 13:40
Thanks for the link, I could solve the problem and use my old model. Basically, yesterday I had to use an old backup of July, because the last Raspbian updates have killed the screen of my Raspberry Pi. I solved the problem by resolving conflicts between the old and new configuration files :robot:

**Comment by Philmasse50** [comment] 2017-05-14 13:02
Rebonjour
j'ai saisie ma clef et la je penses que cela fonctionne.
Merci et bon courage pour ce très bon projet.
Philippe
